### ISSUE TITLE
"Terms & conditions" checkbox on checkout doesn't work using epay payment window

### ISSUE THREAD

**Issue by boxyman** [bambora/checkout-magento-v2.x#19] opened 2017-11-06 11:05 UTC
After updating to Magento 2.2 "Terms & conditions" checkbox on checkout doesn't work.

When clicking "Place order now" I get the error message "Please agree to all terms and conditions before placing order."

When I go to "Stores" > "Terms and Conditions" > "Terms" and set "Applied" to "Automatically" instead of "Manually" then it works.

That remove the checkbox and therefore you can complete the order.

But in EU it is required by law that the checkbox should be there, so it is a critical bug.

**Comment by torlokken** [comment] 2017-11-08 12:20
I can confirm this critical bug, we need a fix asap.

**Comment by AllanWLie** [comment] 2017-11-10 12:34
Hi @boxyman and @torlokken 

The issue have been fixed in the newest release (1.3.1) https://github.com/bambora/checkout-magento-v2.x/releases/latest

Due to pending marked release you will have to follow the upgrade guide in the version changelog

**Closed as completed by AllanWLie** 2017-11-10 12:34 UTC
